<nav class="spine-offsitenav custom">
	<ul>
        <li><a href="https://hardhatclassic.wsu.edu/" target="_blank">Hard Hat Classic</a></li>
        <li style="border-bottom: 1px solid #000 !important;"></li>
		<li><a href="https://wsu.edu" target="_blank">WSU Home</a></li>
	</ul>
	<?php // note that the network menu section is missing as this is a standalone site.  Look to the main theme to re-add it ?>
</nav>